logoText = "R"
description = "记录一点想法"
custom_css = []
custom_js = []

# header
homeHeaderType = "text" # text, img, slide

# navbar
enableThemeChange = true # site color theme

# body
enableBreadcrumb = true
enablePhotoSwipe = true
enableSearch = true
enableGoToTop = true
enableWhoami = false
summaryShape = "classic" # card, classic, compact
archiveGroupByDate = "2006" # "2006-01": group by month, "2006": group by year
archivePaginate = 13
paginateWindow = 1 # setting it to 1 gives 7 buttons, 2 gives 9, etc. If set 1: [1 ... 4 5 6 ... 356] [1 2 3 4 5 ... 356] etc

# whoami
myname = "rragat"
email = "rrcgat@gmail.com"
whoami = "一个心里想学习的人"
useGravatar = false
location = "China"
organization = ""
link = ""

# sidebar
enableBio = true # home page sidebar
enableSidebar = true # if you want to make full width of contents
enableSidebarTags = true # if you want to use tags.
enableSidebarSeries = true
enableSidebarCategories = true
enableToc = true # single page table of contents
enableTocSwitch = true # single page table of contents visibility switch
itemsPerCategory = 5 # maximum number of posts shown in the sidebar.
searchLanguages = ['en'] # lunr multilanguage search. https://github.com/MihaiValentin/lunr-languages

# footer
showPoweredBy = true # show footer text: Powered by Hugo and Zzo theme
showFeedLinks = true # RSS Feed
showSocialLinks = true # email, facebook, twitter ...
enableLangChange = true # show button at bottom left of footer.
themeOptions = ["dark", "light", "hacker", "solarized", "custom"] # select options for site color theme

# comment
enableComment = true
disqus_shortname = ""
commento = false

[utterances]       # https://utteranc.es/
  owner = "rrcgat"              # Your GitHub ID
  repo = "rrcgat.github.io"               # The repo to store comments

[marketing]
  googleAnalytics = ""

[socialOptions]
  email = "mailto:rrcgat@gmail.com"
  twitter = ""
  github = "http://github.com/rrcgat/"
  stack-overflow = ""
  stack-exchange = ""
